[package]
name = "veldmap-data-browser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
veldsdk = { path = "../../../veldcore/sdk/rust" }
veld-ui = { path = "../../../veldstd/ui-service/lib/rust" }
veldmap-api = { path = "../../lib/rust/api" }
veldmap-image = { path = "../../lib/rust/image" }
prost = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"
anyhow = "1.0"
log = "0.4"
lazy_static = "1.4"
tokio = { version = "1.49", features = ["sync", "macros"] }
async-stream = "0.3"
image = "0.25"
tiff = "0.9"
