syntax = "proto3";

package veldmap.app;

message UIEvent {
    veldmap.core.ResourceHandle surface_handle = 1;
    oneof event {
        ClickEvent click = 2;
        KeyEvent key = 3;
        ResizeEvent resize = 4;
        InitEvent init = 5;
        ScrollEvent scroll = 6;
        CursorMovedEvent cursor_moved = 7;
        FrameEvent frame = 8;
    }
}

message FrameEvent {
    float dt = 1;
}

message ClickEvent {
    float x = 1;
    float y = 2;
    uint32 button = 3;
    bool pressed = 4;
}

message ScrollEvent {
    float delta_x = 1;
    float delta_y = 2;
}

message CursorMovedEvent {
    float x = 1;
    float y = 2;
}

message KeyEvent {
    uint32 key_code = 1;
    bool pressed = 2;
}

message ResizeEvent {
    uint32 width = 1;
    uint32 height = 2;
    float scale_factor = 3;
}

message InitEvent {}

import "core.proto";

// Описание того, что Хост должен сделать с окном
message AppDisplayCommand {
    oneof command {
        DrawFrame draw_frame = 1;
    }
}

message DrawFrame {
    veldmap.core.ResourceHandle handle = 1;
    uint32 width = 2;
    uint32 height = 3;
}
