[package]
name = "veldmap-host-system"
version = "0.1.0"
edition = "2021"

[dependencies]
veldmap-host-util = { path = "../../util" }
prost = "0.14"
anyhow = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = "6.0"
uuid = { version = "1.0", features = ["v4"] }

[build-dependencies]
prost-build = "0.14"
