[package]
name = "veldmap-app-desktop-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.1.0"
veldmap-rust-rpc = { path = "../../../../veldcore/sdk/rust/rpc", features = ["pdk"] }
veldmap-logger = { path = "../../../../veldcore/sdk/rust/logger" }
prost = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"
anyhow = "1.0"
log = "0.4"