package: veldmap-data-provider
language: rust
rust:
  dependencies:
    prost: '"0.14"'
    serde: '{ version = "1.0", features = ["derive"] }'
    serde_json: '"1.0"'
    log: '"0.4"'
    anyhow: '"1.0"'
    quick-xml: '"0.36"'
    urlencoding: '"2.1"'
    rusty-s3: '"0.8.1"'
    http: '"1.0"'
    aws-sigv4: '"1.2.2"'
    aws-credential-types: '"1.2.0"'
    aws-smithy-runtime-api: '{ version = "1.1", features = ["client"] }'
    url: '"2.5"'
