name: data-provider
version: 1.0.0

interface:
  inputs:
    download:
      type: module/DownloadRequest
    cancel_download:
      type: module/CancelDownloadRequest
    list_path:
      type: module/ListPathRequest
    search:
      type: module/SearchRequest

  outputs:
    download_started:
      called_by: module/download
      type: module/DownloadStarted
    list_path_result:
      called_by: module/list_path
      type: module/ListPathResponse
    search_result:
      called_by: module/search
      type: module/SearchResponse
    downloaded:
      called_by: network/fs_download_result
      type: module/Downloaded
    download_progress:
      called_by: network/fs_download_progress
      type: module/DownloadProgress

dependencies:
  network:
    subs:
      fs_download_result:
        type: network/FsDownloadResponse
      fs_download_progress:
        type: network/FsDownloadProgress
      http_result:
        type: network/HttpTaskResponse
    calls:
      fs_download:
        called_by: module/download
        type: network/FsDownloadRequest
      http:
        called_by: module/list_path
        type: network/HttpTaskRequest
  tasks:
    subs:
      task_finished:
        type: tasks/TaskFinished
