name: data-provider
version: 1.0.0

interface:
  inputs:
    on_download:
      type: module/DownloadRequest
    on_cancel_download:
      type: module/CancelDownloadRequest
    on_list_path:
      type: module/ListPathRequest
    on_search:
      type: module/SearchRequest

  outputs:
    on_download_started:
      called_by: module/on_download
      type: module/DownloadStarted
    on_list_path_result:
      called_by: module/on_list_path
      type: module/ListPathResponse
    on_search_result:
      called_by: module/on_search
      type: module/SearchResponse
    on_downloaded:
      called_by: network/on_fs_download_result
      type: module/Downloaded
    on_download_progress:
      called_by: network/on_fs_download_progress
      type: module/DownloadProgress

dependencies:
  network:
    subs:
      on_fs_download_result:
        type: network/FsDownloadResponse
      on_fs_download_progress:
        type: network/FsDownloadProgress
      on_http_result:
        type: network/HttpTaskResponse
    calls:
      on_fs_download:
        called_by: module/on_download
        type: network/FsDownloadRequest
      on_http:
        called_by: module/on_list_path
        type: network/HttpTaskRequest
  tasks:
    subs:
      on_task_finished:
        type: tasks/TaskFinished
