[workspace]
members = [
    "data-provider/generated",
    "data-browser/generated",
    "ui-service/generated",
]
resolver = "2"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("pdk"))'] }

[profile.release]
opt-level = "s"
panic = "abort"
lto = true
codegen-units = 1

[profile.release.package.veldmap-data-browser]
opt-level = 3
