[package]
name = "veldmap-app-desktop-client"
version = "0.1.0"
edition = "2021"

[dependencies]
veldmap-core = { path = "../../core" }
veldmap-render = { path = "../../modules/render" }
veldmap-tile-server = { path = "../../modules/tile-server" }
tokio = { version = "1.0", features = ["full"] }
winit = "0.29"
log = "0.4"
env_logger = "0.11"
