//! AUTO-GENERATED BY buildgen/generate.py - DO NOT EDIT
//! Типизированные стабы платформенных топиков (veldcore/interface, схема
//! сервиса `app`). Строки топиков существуют только здесь.

use prost::Message;


/// `app/on_set_surface`
pub fn on_set_surface(msg: &crate::proto::app::SetSurface) {
    crate::abi::publish("app/on_set_surface", msg.encode_to_vec());
}

