//! AUTO-GENERATED BY buildgen/generate.py - DO NOT EDIT
//! Типизированные стабы платформенных топиков (veldcore/proto/tasks.schema.yaml,
//! контракт tasks.proto). Строки топиков существуют только здесь.

use prost::Message;


/// `tasks/cancel`
pub fn cancel(msg: &crate::proto::tasks::TaskCancelRequest) {
    crate::abi::publish("tasks/cancel", msg.encode_to_vec());
}


/// `tasks/grant`
pub fn grant(msg: &crate::proto::tasks::TaskGrantRequest) {
    crate::abi::publish("tasks/grant", msg.encode_to_vec());
}

