//! AUTO-GENERATED BY buildgen/generate.py - DO NOT EDIT
//! Типизированные стабы платформенных топиков (veldcore/proto/tasks.schema.yaml,
//! контракт tasks.proto). Строки топиков существуют только здесь.

use prost::Message;


/// `tasks/on_cancel`
pub fn on_cancel(msg: &crate::proto::tasks::TaskCancelRequest) {
    crate::abi::publish("tasks/on_cancel", msg.encode_to_vec());
}


/// `tasks/on_grant`
pub fn on_grant(msg: &crate::proto::tasks::TaskGrantRequest) {
    crate::abi::publish("tasks/on_grant", msg.encode_to_vec());
}

