[workspace]
members = [
    "lib/rust/api",
    "lib/rust/image",
    "modules/data-provider",
    "apps/data-browser",
]
resolver = "2"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("pdk"))'] }

[profile.release]
opt-level = 3
panic = "abort"
lto = true
codegen-units = 1

[profile.release.package.veldmap-data-browser]
opt-level = 3

[profile.release.package.veldmap-data-provider]
opt-level = "s"
